name: NostrKey
options:
  bundleIdPrefix: com.nostrkey
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  NostrKey:
    type: application
    platform: iOS
    sources:
      - path: NostrKey/App
      - path: NostrKey/Controllers
      - path: NostrKey/Bridge
      - path: NostrKey/Assets.xcassets
      - path: NostrKey/Web
        type: folder
        buildPhase: resources
      - path: NostrKey/Info.plist
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nostrkey.app
        PRODUCT_NAME: NostrKey
        MARKETING_VERSION: "1.0.4"
        CURRENT_PROJECT_VERSION: 5
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "NostrKey/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        ALWAYS_SEARCH_USER_PATHS: NO
